version: '3.8'

networks:
  advproject-bridge:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - php
      - mysql
    networks:
      - advproject-bridge

  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/html
    networks:
      - advproject-bridge

  mysql:
    image: mysql:8
    ports:
      - '33306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser
    networks:
      - advproject-bridge
